# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 33e25ea2f0e19d97ffd84a1b84df7667c79b94e83a438aa6234f8b6243481b75399d24f2d805925f8408631cce57d995b37c57de373373a962db475ffd79f8d2

test:
  secret_key_base: b018ce87e7ca764641651031c08c90d6f88c5e0ec357bdb699c51741ddf40e39c21c94534bc72ba945d14c09b0caecb31e2f1d9e6dd4e6e10c9734a2e8b8f512

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
